use crate::discovery::scenario_asset_paths;
use crate::report::GadugiAdapterGenerationReport;
use crate::schema::{EatmeScenarioAsset, EatmeScenarioStep};
use crate::validation::validate_id;
use anyhow::{Context, Result, bail};
#[path = "gadugi_description.rs"]
mod gadugi_description;
#[path = "gadugi_instructor.rs"]
mod gadugi_instructor;
#[path = "gadugi_schema.rs"]
mod gadugi_schema;

use gadugi_description::generated_description;
use gadugi_instructor::generate_instructor_agentic_adapter;
use gadugi_schema::*;
use std::collections::{BTreeMap, HashSet};
use std::fs;
use std::io::ErrorKind;
use std::path::{Path, PathBuf};

const GENERATED_BY: &str = "eatme-assets gadugi adapter generator";
const GENERATED_FILE_HEADER: &str = "# DO NOT EDIT: generated by eatme-assets from canonical eatme scenario assets.\n# Non-coders: edit the matching source YAML under assets/scenarios/eatme/, then ask a maintainer to run `eatme assets generate-gadugi`.\n";

pub fn generate_gadugi_adapters(root: &Path, check: bool) -> Result<GadugiAdapterGenerationReport> {
    let scenario_root = root.join("assets/scenarios");
    let eatme_root = scenario_root.join("eatme");
    let gadugi_root = scenario_root.join("gadugi");
    let scenario_paths = scenario_asset_paths(&scenario_root)?;
    let mut sources = Vec::new();
    for source_path in scenario_paths
        .iter()
        .filter(|path| path.starts_with(&eatme_root))
    {
        let scenario = read_eatme_scenario(source_path)?;
        let target_path = target_gadugi_path(&gadugi_root, source_path, &scenario)?;
        sources.push((source_path.clone(), scenario, target_path));
    }
    let expected_scenario_asset_count = scenario_paths.len()
        + missing_generated_target_count(
            &scenario_paths,
            sources.iter().map(|(_, _, target_path)| target_path),
        );
    let mut report = GadugiAdapterGenerationReport {
        schema_version: "eatme.assets/gadugi-adapter-generation/v1".into(),
        root: root.display().to_string(),
        generated_count: 0,
        checked_count: 0,
        changed: Vec::new(),
        passed: true,
        errors: Vec::new(),
    };

    if !check {
        fs::create_dir_all(&gadugi_root)
            .with_context(|| format!("creating {}", gadugi_root.display()))?;
    }

    for (source_path, scenario, target_path) in sources {
        let yaml = generate_gadugi_adapter_yaml_for_scenario(
            root,
            &source_path,
            &scenario,
            expected_scenario_asset_count,
        )?;
        report.generated_count += 1;
        if check {
            report.checked_count += 1;
            match fs::read_to_string(&target_path) {
                Ok(existing) if existing == yaml => {}
                Ok(_) => {
                    report.passed = false;
                    report.changed.push(target_path.display().to_string());
                    report.errors.push(format!(
                        "{} is stale; regenerate with `eatme assets generate-gadugi`",
                        target_path.display()
                    ));
                }
                Err(error) => {
                    report.passed = false;
                    report.changed.push(target_path.display().to_string());
                    report.errors.push(format!(
                        "{} is missing or unreadable: {error}",
                        target_path.display()
                    ));
                }
            }
        } else {
            let changed = match fs::read_to_string(&target_path) {
                Ok(existing) => existing != yaml,
                Err(error) if error.kind() == ErrorKind::NotFound => true,
                Err(error) => {
                    return Err(error).with_context(|| {
                        format!("reading generated gadugi adapter {}", target_path.display())
                    });
                }
            };
            if changed {
                fs::write(&target_path, yaml)
                    .with_context(|| format!("writing {}", target_path.display()))?;
                report.changed.push(target_path.display().to_string());
            }
        }
    }

    Ok(report)
}

pub fn generate_gadugi_adapter_yaml(root: &Path, source_path: &Path) -> Result<String> {
    let scenario_root = root.join("assets/scenarios");
    let gadugi_root = scenario_root.join("gadugi");
    let scenario_paths = scenario_asset_paths(&scenario_root)?;
    let scenario = read_eatme_scenario(source_path)?;
    let target_path = target_gadugi_path(&gadugi_root, source_path, &scenario)?;
    let target_already_discovered = scenario_paths.iter().any(|path| path == &target_path);
    let expected_scenario_asset_count =
        scenario_paths.len() + usize::from(!target_already_discovered);
    generate_gadugi_adapter_yaml_for_scenario(
        root,
        source_path,
        &scenario,
        expected_scenario_asset_count,
    )
}

fn target_gadugi_path(
    gadugi_root: &Path,
    source_path: &Path,
    scenario: &EatmeScenarioAsset,
) -> Result<PathBuf> {
    let mut errors = Vec::new();
    validate_id(&scenario.id, "scenario", &mut errors);
    if !errors.is_empty() {
        bail!("{}: {}", source_path.display(), errors.join("; "));
    }
    Ok(gadugi_root.join(format!("{}.yaml", scenario.id)))
}

fn missing_generated_target_count<'a>(
    scenario_paths: &[PathBuf],
    generated_target_paths: impl IntoIterator<Item = &'a PathBuf>,
) -> usize {
    let discovered_paths: HashSet<&Path> = scenario_paths.iter().map(PathBuf::as_path).collect();
    generated_target_paths
        .into_iter()
        .filter(|target_path| !discovered_paths.contains(target_path.as_path()))
        .count()
}

fn generate_gadugi_adapter_yaml_for_scenario(
    root: &Path,
    source_path: &Path,
    scenario: &EatmeScenarioAsset,
    expected_scenario_asset_count: usize,
) -> Result<String> {
    let source_asset = source_path
        .strip_prefix(root)
        .with_context(|| {
            format!(
                "scenario asset {} is not under root {}",
                source_path.display(),
                root.display()
            )
        })?
        .to_string_lossy()
        .replace('\\', "/");
    if scenario.id.is_empty() {
        bail!("{} must define id", source_path.display());
    }

    let timeout_ms = scenario_timeout_ms(scenario);
    let launch_timeout = scenario
        .timeouts
        .get("launch_seconds")
        .copied()
        .unwrap_or(900);
    let run_id = format!("gadugi-{}", scenario.id);

    if scenario.kind == "instructor_agentic_flow" {
        return generate_instructor_agentic_adapter(scenario, source_asset, timeout_ms);
    }

    let mut steps = Vec::with_capacity(scenario.steps.len());
    let mut assertions = Vec::with_capacity(scenario.steps.len());
    for step in &scenario.steps {
        let step_name = step_title(&step.id);
        let exit_code = expected_exit_code(scenario, step);
        let stdout_contains = expected_stdout(scenario, step, expected_scenario_asset_count);

        assertions.push(generated_assertion(
            step,
            "eatme-cli-agent",
            &step_name,
            exit_code,
            &stdout_contains,
        ));
        steps.push(generated_step(
            step,
            &run_id,
            launch_timeout,
            step_name,
            exit_code,
            stdout_contains,
        ));
    }

    let adapter = GeneratedGadugiAdapter {
        name: format!("Eatme {}", scenario.title),
        description: generated_description(&source_asset, scenario),
        version: "1.0.0".into(),
        config: GeneratedConfig {
            timeout: timeout_ms,
            retries: 0,
            parallel: false,
        },
        environment: GeneratedEnvironment {
            requires: required_environment(scenario),
            optional: vec!["RUN_ID".into(), "EATME_REPO".into()],
        },
        agents: vec![GeneratedAgent {
            name: "eatme-cli-agent".into(),
            agent_type: "system".into(),
            config: GeneratedAgentConfig {
                shell: Some("bash".into()),
                cwd: Some(".".into()),
                timeout: timeout_ms,
                capture_output: Some(true),
                persona_asset: None,
                scenario_asset: None,
            },
        }],
        steps,
        assertions,
        metadata: GeneratedMetadata {
            source_eatme_asset: source_asset,
            generated_by: GENERATED_BY.into(),
            tags: vec![
                "alice".into(),
                "eatme".into(),
                "gadugi".into(),
                "outside-in".into(),
                scenario.id.clone(),
            ],
            priority: "critical".into(),
            author: "eatme".into(),
            test_type: match scenario.kind.as_str() {
                "alice_real_ui_action_contract" => "ui-action-contract",
                _ => "launch-smoke",
            }
            .into(),
        },
    };

    render_yaml(adapter)
}

fn read_eatme_scenario(path: &Path) -> Result<EatmeScenarioAsset> {
    let content = fs::read_to_string(path)
        .with_context(|| format!("reading eatme scenario asset {}", path.display()))?;
    serde_yaml::from_str(&content)
        .with_context(|| format!("parsing eatme scenario YAML {}", path.display()))
}

fn render_yaml(adapter: GeneratedGadugiAdapter) -> Result<String> {
    let serialized = serde_yaml::to_string(&adapter).context("serializing gadugi adapter YAML")?;
    let mut yaml = String::with_capacity(GENERATED_FILE_HEADER.len() + serialized.len() + 1);
    yaml.push_str(GENERATED_FILE_HEADER);
    yaml.push_str(&serialized);
    if !yaml.ends_with('\n') {
        yaml.push('\n');
    }
    Ok(yaml)
}

fn generated_step(
    step: &EatmeScenarioStep,
    run_id: &str,
    launch_timeout: u64,
    step_name: String,
    exit_code: u64,
    stdout_contains: Vec<String>,
) -> GeneratedStep {
    let command = repository_command(step.command.trim(), run_id);
    GeneratedStep {
        name: step_name,
        agent: "eatme-cli-agent".into(),
        action: "execute_command".into(),
        params: BTreeMap::from([("command".into(), command)]),
        expect: GeneratedExpect {
            exit_code: Some(exit_code),
            stdout_contains: Some(stdout_contains),
            output_contains: None,
        },
        timeout: step_timeout_ms(&step.id, launch_timeout),
    }
}

fn generated_assertion(
    step: &EatmeScenarioStep,
    agent: &str,
    step_name: &str,
    exit_code: u64,
    expected_stdout: &[String],
) -> GeneratedAssertion {
    if exit_code == 0 {
        return GeneratedAssertion {
            name: format!("{} succeeds", step.id),
            assertion_type: "command_success".into(),
            agent: agent.into(),
            params: BTreeMap::from([("step".into(), step_name.into())]),
        };
    }

    GeneratedAssertion {
        name: format!("{} expected failure is explicit", step.id),
        assertion_type: "output_contains_all".into(),
        agent: agent.into(),
        params: BTreeMap::from([
            ("step".into(), step_name.into()),
            ("required_strings".into(), expected_stdout.join("\n")),
        ]),
    }
}

fn scenario_timeout_ms(scenario: &EatmeScenarioAsset) -> u64 {
    scenario
        .timeouts
        .get("scenario_seconds")
        .or_else(|| scenario.timeouts.get("agentic_seconds"))
        .copied()
        .unwrap_or(1800)
        * 1000
}

fn repository_command(command: &str, run_id: &str) -> String {
    format!("cd \"${{EATME_REPO:-.}}\"\nexport RUN_ID=\"${{RUN_ID:-{run_id}}}\"\n{command}")
}

fn step_title(id: &str) -> String {
    let mut title = String::new();
    for part in id.split('-').filter(|part| !part.is_empty()) {
        if !title.is_empty() {
            title.push(' ');
        }
        let mut chars = part.chars();
        if let Some(first) = chars.next() {
            title.extend(first.to_uppercase());
            title.push_str(chars.as_str());
        }
    }
    title
}

fn step_timeout_ms(step_id: &str, launch_timeout: u64) -> u64 {
    if step_id.contains("launch") {
        launch_timeout * 1000
    } else {
        60_000
    }
}

fn expected_exit_code(scenario: &EatmeScenarioAsset, step: &EatmeScenarioStep) -> u64 {
    if is_launch_step(&step.id, &step.command) && scenario.kind == "alice_real_ui_action_contract" {
        1
    } else {
        0
    }
}

fn expected_stdout(
    scenario: &EatmeScenarioAsset,
    step: &EatmeScenarioStep,
    expected_scenario_asset_count: usize,
) -> Vec<String> {
    let step_id = step.id.as_str();
    let command = step.command.as_str();
    if command.contains("assets validate") {
        let mut expected = vec!["\"passed\": true".into()];
        if command.contains("--path") {
            expected.push(format!("\"id\": \"{}\"", scenario.id));
        } else {
            expected.push(format!(
                "\"scenario_asset_count\": {expected_scenario_asset_count}"
            ));
        }
        return expected;
    }
    if step_id.contains("dependencies") {
        return vec!["\"all_required_available\": true".into()];
    }
    if step_id.contains("discover") {
        return vec!["\"alice_ide_jar_exists\": true".into()];
    }
    if is_launch_step(step_id, command) {
        return launch_expected_stdout(scenario, step);
    }
    Vec::new()
}

fn is_launch_step(step_id: &str, command: &str) -> bool {
    step_id.contains("launch")
        || step_id.contains("smoke")
        || command.contains("alice launch-smoke")
}

fn launch_expected_stdout(scenario: &EatmeScenarioAsset, step: &EatmeScenarioStep) -> Vec<String> {
    let evidence = step.evidence.join("\n").to_lowercase();
    let mut expected = vec![format!("\"scenario_id\": \"{}\"", scenario.id)];
    if scenario.kind == "alice_real_ui_action_contract" {
        expected.push("\"failure_category\":".into());
    } else {
        expected.push("\"failure_category\": null".into());
    }
    expected.push("\"real_alice_execution_evidence\": {".into());

    if evidence.contains("screenshot or window") {
        expected.push("\"startup_window_or_screenshot\": {".into());
    } else if evidence.contains("screenshot") {
        expected.push("\"startup_screenshot\": {".into());
    }

    for assertion in [
        "specific_alice_window_detected",
        "activate_alice_window_ui_action",
        "save_project_desktop_shortcut_dispatch",
        "place_object_precondition_no_go_probe",
        "place_object_ui_action",
        "edit_procedure_ui_action",
        "run_world_ui_action",
        "save_project_ui_action",
        "ui_action_artifact_captured",
    ] {
        if evidence.contains(assertion) {
            expected.push(format!("\"{assertion}\": {{"));
        }
    }
    if evidence.contains("ui-action-contract.json") {
        expected.push("\"ui_action_contract\": {".into());
    }
    if evidence.contains("africa.a3p") {
        expected.push("africa.a3p".into());
    }
    if evidence.contains("assertions all pass") || evidence.contains("passed=true") {
        expected.push("\"passed\": true".into());
    }
    expected
}

fn required_environment(scenario: &EatmeScenarioAsset) -> Vec<String> {
    let mut required = vec!["ALICE_HOME".into()];
    if scenario
        .real_alice
        .as_ref()
        .map(|real_alice| real_alice.gated_by == "EATME_REAL_ALICE=1")
        .unwrap_or(false)
    {
        required.push("EATME_REAL_ALICE".into());
    }
    required
}

#[cfg(test)]
#[path = "gadugi_tests.rs"]
mod gadugi_tests;
