use crate::discovery::scenario_asset_paths;
use crate::report::GadugiAdapterGenerationReport;
use crate::schema::{EatmeScenarioAsset, EatmeScenarioStep};
use crate::validation::validate_id;
use anyhow::{Context, Result, bail};
#[path = "gadugi_instructor.rs"]
mod gadugi_instructor;
#[path = "gadugi_schema.rs"]
mod gadugi_schema;
#[path = "gadugi_step_blocks.rs"]
mod gadugi_step_blocks;

use gadugi_instructor::generate_instructor_agentic_adapter;
use gadugi_schema::*;
use gadugi_step_blocks::{
    launch_expected_stdout, preflight_check_dependencies_patterns,
    preflight_validate_assets_patterns,
};
use std::collections::{BTreeMap, HashSet};
use std::fs;
use std::path::{Path, PathBuf};

const GENERATED_BY: &str = "eatme-assets gadugi adapter generator";
const GENERATED_FILE_HEADER: &str = "# DO NOT EDIT: generated by eatme-assets from canonical eatme scenario assets.\n# Non-coders: edit the matching source YAML under assets/scenarios/eatme/, then ask a maintainer to run `eatme assets generate-gadugi`.\n";

pub fn generate_gadugi_adapters(root: &Path, check: bool) -> Result<GadugiAdapterGenerationReport> {
    let scenario_root = root.join("assets/scenarios");
    let eatme_root = scenario_root.join("eatme");
    let gadugi_root = scenario_root.join("gadugi");
    let scenario_paths = scenario_asset_paths(&scenario_root)?;
    let mut sources = Vec::new();
    for source_path in scenario_paths
        .iter()
        .filter(|path| path.starts_with(&eatme_root))
    {
        let scenario = read_eatme_scenario(source_path)?;
        let target_path = target_gadugi_path(&gadugi_root, source_path, &scenario)?;
        sources.push((source_path.clone(), scenario, target_path));
    }
    let expected_scenario_asset_count = scenario_paths.len()
        + missing_generated_target_count(
            &scenario_paths,
            sources.iter().map(|(_, _, target_path)| target_path),
        );
    let mut report = GadugiAdapterGenerationReport {
        schema_version: "eatme.assets/gadugi-adapter-generation/v1".into(),
        root: root.display().to_string(),
        generated_count: 0,
        checked_count: 0,
        changed: Vec::new(),
        passed: true,
        errors: Vec::new(),
    };

    if !check {
        fs::create_dir_all(&gadugi_root)
            .with_context(|| format!("creating {}", gadugi_root.display()))?;
    }

    for (source_path, scenario, target_path) in sources {
        let yaml = generate_gadugi_adapter_yaml_for_scenario(
            root,
            &source_path,
            &scenario,
            expected_scenario_asset_count,
        )?;
        report.generated_count += 1;
        if check {
            report.checked_count += 1;
            match fs::read_to_string(&target_path) {
                Ok(existing) if existing == yaml => {}
                Ok(_) => {
                    report.passed = false;
                    report.changed.push(target_path.display().to_string());
                    report.errors.push(format!(
                        "{} is stale; regenerate with `eatme assets generate-gadugi`",
                        target_path.display()
                    ));
                }
                Err(error) => {
                    report.passed = false;
                    report.changed.push(target_path.display().to_string());
                    report.errors.push(format!(
                        "{} is missing or unreadable: {error}",
                        target_path.display()
                    ));
                }
            }
        } else {
            let changed = fs::read_to_string(&target_path)
                .map(|existing| existing != yaml)
                .unwrap_or(true);
            if changed {
                fs::write(&target_path, yaml)
                    .with_context(|| format!("writing {}", target_path.display()))?;
                report.changed.push(target_path.display().to_string());
            }
        }
    }

    Ok(report)
}

pub fn generate_gadugi_adapter_yaml(root: &Path, source_path: &Path) -> Result<String> {
    let scenario_root = root.join("assets/scenarios");
    let gadugi_root = scenario_root.join("gadugi");
    let scenario_paths = scenario_asset_paths(&scenario_root)?;
    let scenario = read_eatme_scenario(source_path)?;
    let target_path = target_gadugi_path(&gadugi_root, source_path, &scenario)?;
    let target_already_discovered = scenario_paths.iter().any(|path| path == &target_path);
    let expected_scenario_asset_count =
        scenario_paths.len() + usize::from(!target_already_discovered);
    generate_gadugi_adapter_yaml_for_scenario(
        root,
        source_path,
        &scenario,
        expected_scenario_asset_count,
    )
}

fn target_gadugi_path(
    gadugi_root: &Path,
    source_path: &Path,
    scenario: &EatmeScenarioAsset,
) -> Result<PathBuf> {
    let mut errors = Vec::new();
    validate_id(&scenario.id, "scenario", &mut errors);
    if !errors.is_empty() {
        bail!("{}: {}", source_path.display(), errors.join("; "));
    }
    Ok(gadugi_root.join(format!("{}.yaml", scenario.id)))
}

fn discovered_path_set(paths: &[PathBuf]) -> HashSet<&Path> {
    paths.iter().map(PathBuf::as_path).collect()
}

fn missing_generated_target_count<'a>(
    scenario_paths: &[PathBuf],
    generated_target_paths: impl IntoIterator<Item = &'a PathBuf>,
) -> usize {
    let discovered_paths = discovered_path_set(scenario_paths);
    generated_target_paths
        .into_iter()
        .filter(|target_path| !discovered_paths.contains(target_path.as_path()))
        .count()
}

fn generate_gadugi_adapter_yaml_for_scenario(
    root: &Path,
    source_path: &Path,
    scenario: &EatmeScenarioAsset,
    expected_scenario_asset_count: usize,
) -> Result<String> {
    let source_asset = source_path
        .strip_prefix(root)
        .with_context(|| {
            format!(
                "scenario asset {} is not under root {}",
                source_path.display(),
                root.display()
            )
        })?
        .to_string_lossy()
        .replace('\\', "/");
    if scenario.id.is_empty() {
        bail!("{} must define id", source_path.display());
    }

    let timeout_ms = scenario_timeout_ms(scenario);
    let launch_timeout = scenario
        .timeouts
        .get("launch_seconds")
        .copied()
        .unwrap_or(900);
    let run_id = format!("gadugi-{}", scenario.id);

    if scenario.kind == "instructor_agentic_flow" {
        return generate_instructor_agentic_adapter(
            scenario,
            source_asset,
            timeout_ms,
            launch_timeout,
            expected_scenario_asset_count,
        );
    }

    let steps = scenario
        .steps
        .iter()
        .map(|step| {
            generated_step(
                scenario,
                step,
                &run_id,
                launch_timeout,
                expected_scenario_asset_count,
            )
        })
        .collect::<Result<Vec<_>>>()?;
    let assertions = scenario
        .steps
        .iter()
        .map(|step| {
            generated_assertion(
                scenario,
                step,
                "eatme-cli-agent",
                expected_scenario_asset_count,
            )
        })
        .collect::<Result<Vec<_>>>()?;

    let adapter = GeneratedGadugiAdapter {
        name: format!("Eatme {}", scenario.title),
        description: format!(
            "Gadugi-compatible CLI scenario generated from {source_asset}. Alice desktop behavior remains owned by eatme; {}.{}",
            generated_evidence_scope(scenario),
            generated_boundary_note(scenario)
        ),
        version: "1.0.0".into(),
        config: GeneratedConfig {
            timeout: timeout_ms,
            retries: 0,
            parallel: false,
        },
        environment: GeneratedEnvironment {
            requires: required_environment(scenario),
            optional: optional_environment(scenario),
        },
        agents: vec![GeneratedAgent {
            name: "eatme-cli-agent".into(),
            agent_type: "system".into(),
            config: GeneratedAgentConfig {
                shell: Some("bash".into()),
                cwd: Some(".".into()),
                timeout: timeout_ms,
                capture_output: Some(true),
                persona_asset: None,
                scenario_asset: None,
            },
        }],
        steps,
        assertions,
        metadata: GeneratedMetadata {
            source_eatme_asset: source_asset,
            generated_by: GENERATED_BY.into(),
            tags: vec![
                "alice".into(),
                "eatme".into(),
                "gadugi".into(),
                "outside-in".into(),
                scenario.id.clone(),
            ],
            priority: "critical".into(),
            author: "eatme".into(),
            test_type: match scenario.kind.as_str() {
                "alice_real_ui_action_contract" => "ui-action-contract",
                "alice_objects_first_workflow" => "objects-first-workflow",
                "alice_howto_user_journey" => "howto-user-journey",
                _ => "startup-check",
            }
            .into(),
        },
    };

    render_yaml(adapter)
}

fn generated_evidence_scope(scenario: &EatmeScenarioAsset) -> &'static str {
    if scenario.id == "starter-project-open-save-export-preflight" {
        return "gadugi invokes eatme commands, records bounded starter-world and readiness-gap artifacts, checks eatme launch evidence, and points reviewers to separate LookingGlass save/reopen/export evidence";
    }

    if scenario.id == "vr-camera-locomotion-journey" {
        return "gadugi invokes eatme commands, checks manifest-level desktop evidence, records VR preflight artifacts, and runs bounded LookingGlass camera comfort API evidence without claiming native headset VR support";
    }

    if scenario.kind == "alice_howto_user_journey" {
        return "gadugi invokes eatme commands for a scenario-specific Alice user journey and checks the expected evidence";
    }

    "gadugi invokes eatme commands and checks manifest-level evidence only"
}

fn generated_boundary_note(scenario: &EatmeScenarioAsset) -> &'static str {
    if scenario.id == "starter-project-open-save-export-preflight" {
        return " This automation scenario keeps honest limits: opened starter project with manifest/log/window/screenshot evidence and bounded starter-world and readiness-gap artifacts only; separate LookingGlass save/reopen/export evidence is required for web parity; not full UI automation, not creative assessment, not learner-world grading, not complete Alice coverage, not visible rendering correctness proof, and not first-lesson completion.";
    }

    let text =
        format!("{}\n{}", scenario.purpose, scenario.unsupported_policy).to_ascii_lowercase();
    if text.contains("not full ui automation")
        && text.contains("not creative assessment")
        && text.contains("not learner-world grading")
    {
        " This adapter preserves the source boundary: not full UI automation, not creative assessment, and not learner-world grading."
    } else {
        ""
    }
}

fn read_eatme_scenario(path: &Path) -> Result<EatmeScenarioAsset> {
    let content = fs::read_to_string(path)
        .with_context(|| format!("reading eatme scenario asset {}", path.display()))?;
    serde_yaml::from_str(&content)
        .with_context(|| format!("parsing eatme scenario YAML {}", path.display()))
}

fn render_yaml(adapter: GeneratedGadugiAdapter) -> Result<String> {
    let mut yaml = GENERATED_FILE_HEADER.to_string();
    yaml.push_str(&serde_yaml::to_string(&adapter).context("serializing gadugi adapter YAML")?);
    if !yaml.ends_with('\n') {
        yaml.push('\n');
    }
    Ok(yaml)
}

fn generated_step(
    scenario: &EatmeScenarioAsset,
    step: &EatmeScenarioStep,
    run_id: &str,
    launch_timeout: u64,
    expected_scenario_asset_count: usize,
) -> Result<GeneratedStep> {
    let command = repository_command(&command_with_stdout_markers(step.command.trim()), run_id);
    Ok(GeneratedStep {
        name: step_title(&step.id),
        agent: "eatme-cli-agent".into(),
        action: "execute_command".into(),
        params: BTreeMap::from([("command".into(), command)]),
        expect: GeneratedExpect {
            exit_code: Some(expected_exit_code(scenario, step)),
            stdout_contains: Some(expected_stdout(
                scenario,
                step,
                expected_scenario_asset_count,
            )?),
            output_contains: None,
        },
        timeout: step_timeout_ms(&step.id, launch_timeout),
    })
}

fn command_success_assertion(step_id: &str, agent: &str) -> GeneratedAssertion {
    GeneratedAssertion {
        name: format!("{step_id} succeeds"),
        assertion_type: "command_success".into(),
        agent: agent.into(),
        params: BTreeMap::from([("step".into(), step_title(step_id))]),
    }
}

fn generated_assertion(
    scenario: &EatmeScenarioAsset,
    step: &EatmeScenarioStep,
    agent: &str,
    expected_scenario_asset_count: usize,
) -> Result<GeneratedAssertion> {
    if expected_exit_code(scenario, step) == 0 {
        return Ok(command_success_assertion(&step.id, agent));
    }

    Ok(GeneratedAssertion {
        name: format!("{} expected failure is explicit", step.id),
        assertion_type: "output_contains_all".into(),
        agent: agent.into(),
        params: BTreeMap::from([
            ("step".into(), step_title(&step.id)),
            (
                "required_strings".into(),
                expected_stdout(scenario, step, expected_scenario_asset_count)?.join("\n"),
            ),
        ]),
    })
}

fn scenario_timeout_ms(scenario: &EatmeScenarioAsset) -> u64 {
    scenario
        .timeouts
        .get("scenario_seconds")
        .or_else(|| scenario.timeouts.get("agentic_seconds"))
        .copied()
        .unwrap_or(1800)
        * 1000
}

fn repository_command(command: &str, run_id: &str) -> String {
    format!("cd \"${{EATME_REPO:-.}}\"\nexport RUN_ID=\"${{RUN_ID:-{run_id}}}\"\n{command}")
}

fn command_with_stdout_markers(command: &str) -> String {
    if !is_executable_cargo_test_command(command) {
        return command.to_owned();
    }
    let markers = cargo_test_success_markers(command);
    if markers.is_empty() {
        return command.to_owned();
    }
    let marker_lines = markers
        .into_iter()
        .map(|marker| format!("printf \"%s\\n\" \"{marker}\""))
        .collect::<Vec<_>>()
        .join("\n");
    format!("set -e\n{command}\n{marker_lines}")
}

fn is_executable_cargo_test_command(command: &str) -> bool {
    let trimmed = command.trim_start();
    let first_line = trimmed.lines().next().unwrap_or(trimmed);
    command_contains_executed_cargo_test(first_line)
        || command_executable_regions(command)
            .iter()
            .any(|region| command_contains_executed_cargo_test(region))
}

fn command_executable_regions(command: &str) -> Vec<String> {
    let mut regions = Vec::new();
    let mut in_heredoc = false;
    for line in command.lines() {
        let trimmed = line.trim();
        if in_heredoc {
            if trimmed == "EOF" {
                in_heredoc = false;
            }
            continue;
        }
        if trimmed.contains("<<EOF") {
            in_heredoc = true;
            regions.push(trimmed.split("<<EOF").next().unwrap_or("").to_owned());
            continue;
        }
        regions.push(trimmed.to_owned());
    }
    regions
}

fn command_contains_executed_cargo_test(command: &str) -> bool {
    let trimmed = command.trim_start();
    trimmed.starts_with("cargo test ")
        || trimmed.contains(" cargo test ")
        || trimmed.starts_with("cd ") && trimmed.contains("&& cargo test ")
        || trimmed.starts_with("bash -lc 'cargo test ")
}

fn step_title(id: &str) -> String {
    id.split('-')
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(first) => format!("{}{}", first.to_uppercase(), chars.as_str()),
                None => String::new(),
            }
        })
        .collect::<Vec<_>>()
        .join(" ")
}

fn step_timeout_ms(step_id: &str, launch_timeout: u64) -> u64 {
    if step_id.contains("launch") || step_id.contains("howto") || step_id.contains("full-path") {
        launch_timeout * 1000
    } else if step_id.contains("setup-readiness") {
        300_000
    } else if step_id.contains("class-behavior") {
        300_000
    } else {
        60_000
    }
}

fn expected_exit_code(scenario: &EatmeScenarioAsset, step: &EatmeScenarioStep) -> u64 {
    if is_launch_step(&step.id, &step.command) && scenario.kind == "alice_real_ui_action_contract" {
        1
    } else {
        0
    }
}
fn expected_stdout(
    scenario: &EatmeScenarioAsset,
    step: &EatmeScenarioStep,
    expected_scenario_asset_count: usize,
) -> Result<Vec<String>> {
    let step_id = step.id.as_str();
    let command = step.command.as_str();
    if command.contains("assets validate") {
        if command.contains("--path") {
            return Ok(vec![
                "\"passed\": true".into(),
                format!("\"id\": \"{}\"", scenario.id),
            ]);
        }
        return Ok(preflight_validate_assets_patterns(
            expected_scenario_asset_count,
        ));
    }
    if step_id.contains("dependencies") {
        return Ok(preflight_check_dependencies_patterns());
    }
    if step_id.contains("discover") {
        return Ok(vec!["\"alice_ide_jar_exists\": true".into()]);
    }
    if is_launch_step(step_id, command) {
        return Ok(launch_expected_stdout(scenario, step));
    }
    let expected = evidence_backed_expected_stdout(step);
    if !expected.is_empty() {
        return Ok(expected);
    }
    bail!(
        "{} step {} generated Gadugi stdout assertions would be empty; add a supported command pattern or explicit evidence-bearing output",
        scenario.id,
        step.id
    )
}

fn evidence_backed_expected_stdout(step: &EatmeScenarioStep) -> Vec<String> {
    let command = step.command.as_str();
    let mut expected = Vec::new();

    if command.contains("wrote=") {
        expected.extend(wrote_stdout_markers(command));
        expected.dedup();
        return expected;
    }
    if command.contains("npm test --") {
        expected.extend(test_command_targets(command));
        expected.extend(printf_evidence_markers(command));
        expected.dedup();
        return expected;
    }
    if command.contains("npx playwright test") {
        expected.extend(test_command_targets(command));
        expected.extend(printf_evidence_markers(command));
        expected.dedup();
        return expected;
    }
    if command.contains("cargo test ") {
        expected.extend(cargo_test_success_markers(command));
        expected.push("test result: ok".into());
        expected.dedup();
        return expected;
    }
    if command.contains("printf ") {
        expected.extend(printf_evidence_markers(command));
        expected.extend(durable_evidence_terms(&step.evidence));
        expected.dedup();
        return expected;
    }
    if command.trim_start().starts_with("inspect ") {
        expected.push(command.trim_start_matches("inspect ").trim().into());
        expected.extend(durable_evidence_terms(&step.evidence));
        expected.dedup();
        return expected;
    }
    expected
}

fn wrote_stdout_markers(command: &str) -> Vec<String> {
    let mut markers = vec!["wrote=".to_owned()];
    let emitted = command
        .split("printf")
        .filter(|segment| segment.contains("wrote="))
        .collect::<Vec<_>>()
        .join("\n");
    if command.contains("wrote=$template")
        && command.contains("comfort-playtest-guidance-template.md")
    {
        markers.push("comfort-playtest-guidance-template.md".into());
        return markers;
    }
    for marker in [
        "a3p-save-load-parity-gaps.md",
        "gallery-media-parity-gaps.md",
        "story-api-runtime-parity-gaps.md",
        "starter-world-change-note.txt",
        "run-observe-readiness-gaps.txt",
        "starter-project-readiness-report.txt",
        "vr-preflight.txt",
        "vr-fallback-evidence.md",
        "agentic-review-guidance.txt",
        "vr-player-preflight.txt",
        "vr-player-fallback-evidence.md",
        "comfort-playtest-guidance.md",
    ] {
        if emitted.contains(marker) {
            markers.push(marker.into());
        }
    }
    markers
}

fn test_command_targets(command: &str) -> Vec<String> {
    command
        .split_whitespace()
        .filter_map(|part| {
            let trimmed = part.trim_matches('\'').trim_matches('"').trim_matches(';');
            (trimmed.ends_with(".test.ts")
                || trimmed.ends_with(".spec.ts")
                || trimmed.ends_with("_e2e")
                || trimmed.ends_with("_coverage")
                || trimmed.ends_with("_integration")
                || trimmed.ends_with("_resilience")
                || trimmed.ends_with("_support")
                || trimmed.ends_with("_management")
                || trimmed.ends_with("_real"))
            .then(|| trimmed.to_owned())
        })
        .collect()
}

fn cargo_test_success_markers(command: &str) -> Vec<String> {
    test_command_targets(command)
        .into_iter()
        .map(|target| format!("cargo-test-ok={target}"))
        .collect()
}

fn printf_evidence_markers(command: &str) -> Vec<String> {
    let mut markers = Vec::new();
    for marker in [
        "migration_fields=alice2-intent,alice3-workflow,vocabulary-delta,visible-student-evidence",
        "required_evidence=keep-adapt-retire,current-artifact,student-reflection",
        "import_fields=source,license,scale,orientation,texture-visibility,issue,fallback",
        "readiness_fields=install,java,graphics,storage,account,fallback",
        "starter_world_change=",
        "run_or_observe_attempt=",
        "save_reopen_export_readiness_gaps=",
        "real_vr_available=",
        "required_evidence=",
        "lookingglass-class-ui-evidence=export-import-instance-save-reopen",
        "wrote=",
        "a3p-save-load-parity-gaps.md",
        "gallery-media-parity-gaps.md",
        "story-api-runtime-parity-gaps.md",
        "starter-world-change-note.txt",
        "run-observe-readiness-gaps.txt",
        "starter-project-readiness-report.txt",
        "agentic_review_mode=",
        "perspective_choice=",
        "comfort_constraint=",
        "fallback_evidence=",
    ] {
        if command.contains(marker) {
            markers.push(marker.into());
        }
    }
    markers
}

fn durable_evidence_terms(evidence: &[String]) -> Vec<String> {
    let text = evidence.join("\n");
    let lower = text.to_lowercase();
    let mut terms = Vec::new();
    for (needle, term) in [
        ("guidance-only", "guidance-only"),
        (
            "automatic alice 2 conversion",
            "automatic Alice 2 conversion",
        ),
        ("converted alice 3 project", "converted Alice 3 project"),
        ("class behavior package", "class behavior package"),
        ("modified class type", "modified class type"),
        ("different aliceproject", "different AliceProject"),
        ("project persistence", "project persistence"),
        ("behavior persistence", "behavior persistence"),
        ("alice-web.teacher-share/v1", "alice-web.teacher-share/v1"),
        ("teacher-share-metadata", "teacher-share-metadata"),
        ("sha256", "sha256"),
        ("passed=true", "passed=true"),
        ("real_vr_available=false", "real_vr_available=false"),
        ("real_vr_available=true", "real_vr_available=true"),
    ] {
        if lower.contains(needle) {
            terms.push(term.into());
        }
    }
    terms
}

fn is_launch_step(step_id: &str, command: &str) -> bool {
    step_id.contains("launch")
        || step_id.contains("smoke")
        || command.contains("alice launch-smoke")
        || command.contains("alice run-howto")
        || command.contains("alice run-objects-first-world")
        || command.contains("alice objects-first-full-path")
}

fn required_environment(scenario: &EatmeScenarioAsset) -> Vec<String> {
    let mut required = Vec::new();
    let commands = scenario
        .steps
        .iter()
        .map(|step| step.command.as_str())
        .collect::<Vec<_>>()
        .join("\n");
    for (name, marker) in [
        ("ALICE_HOME", "ALICE_HOME"),
        ("EATME_REAL_ALICE", "EATME_REAL_ALICE"),
        ("LOOKINGGLASS_HOME", "LOOKINGGLASS_HOME"),
    ] {
        if commands.contains(marker) {
            required.push(name.into());
        }
    }

    required
}

fn optional_environment(scenario: &EatmeScenarioAsset) -> Vec<String> {
    let mut optional = vec!["RUN_ID".into(), "EATME_REPO".into()];
    let commands = scenario
        .steps
        .iter()
        .map(|step| step.command.as_str())
        .collect::<Vec<_>>()
        .join("\n");
    for (name, marker) in [
        ("EATME_REAL_VR", "EATME_REAL_VR"),
        ("VR_HEADSET_AVAILABLE", "VR_HEADSET_AVAILABLE"),
    ] {
        if commands.contains(marker) {
            optional.push(name.into());
        }
    }
    for variable in [
        "ALICE_WEB_URL",
        "ALICE_LOCAL_API_TOKEN",
        "EATME_SETUP_READINESS_SCENARIO",
    ] {
        if commands.contains(variable) && !optional.iter().any(|entry| entry == variable) {
            optional.push(variable.into());
        }
    }
    optional
}
#[cfg(test)]
#[path = "gadugi_tests.rs"]
mod gadugi_tests;
