[package]
name = "eatme-alice"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
eatme-core = { path = "../eatme-core" }
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true

[dev-dependencies]
eatme-assets = { path = "../eatme-assets" }
eatme-test-support = { path = "../eatme-test-support" }
regex = "1"
zip = "2"
